/**
 * Conteúdo dos documentos legais (Termos de Uso, Política de Privacidade,
 * Medidas Antipirataria). Texto integral extraído dos .docx oficiais em
 * /ajustes. Renderizado pelas rotas públicas /termos, /privacidade e
 * /medidas-antipirataria e referenciado no cadastro e no menu do perfil.
 */

export type LegalBlock = { type: "heading" | "p"; text: string };

export type LegalDoc = {
  slug: "termos" | "privacidade" | "medidas-antipirataria";
  title: string;
  /** Subtítulo curto exibido no topo da página. */
  subtitle: string;
  blocks: LegalBlock[];
};

export const LEGAL_DOCS: LegalDoc[] = [
  {
    slug: "termos",
    title: "Termos de Uso",
    subtitle: "Última atualização: 08/06/2026.",
    blocks: [
      { type: "heading", text: "SEÇÃO 1 – IDENTIFICAÇÃO DA PLATAFORMA" },
      { type: "p", text: "A Plataforma de Avaliação de Propostas Comerciais Solar Buy-Side (\"Plataforma\") é operada pela Buy-Side Soluções Inova Simples, pessoa jurídica de direito privado, inscrita no CNPJ nº 55.463.006/0001-80, com sede na Av. Bento Munhoz da Rocha Netto, nº 632, 19º Andar, Salas 1905, 1906, 1907 e 1908 – EVOA, CEP 87.030-010, Maringá – Paraná." },
      { type: "p", text: "Ao acessar ou utilizar a Plataforma, o Usuário declara ter lido, compreendido e aceitado integralmente os presentes Termos de Uso." },
      { type: "heading", text: "SEÇÃO 2 – OBJETO DA PLATAFORMA" },
      { type: "p", text: "A Plataforma Solar Buy-Side tem como finalidade auxiliar consumidores, empresas e investidores na análise comparativa de propostas comerciais de sistemas fotovoltaicos por meio de avaliações técnicas, econômicas, comerciais e reputacionais elaboradas mediante metodologia proprietária." },
      { type: "p", text: "As informações disponibilizadas possuem caráter exclusivamente informativo e consultivo, destinando-se a apoiar o processo de tomada de decisão do Usuário." },
      { type: "heading", text: "SEÇÃO 3 – ELEGIBILIDADE E CADASTRO" },
      { type: "p", text: "O acesso à Plataforma exige cadastro prévio mediante criação de login e senha." },
      { type: "p", text: "O Usuário compromete-se a:" },
      { type: "p", text: "I – fornecer informações verdadeiras, completas e atualizadas;" },
      { type: "p", text: "II – manter a confidencialidade de suas credenciais de acesso;" },
      { type: "p", text: "III – não compartilhar sua conta com terceiros;" },
      { type: "p", text: "IV – utilizar a Plataforma apenas para finalidades lícitas e compatíveis com estes Termos." },
      { type: "p", text: "O Usuário responde integralmente por todas as atividades realizadas por meio de sua conta." },
      { type: "heading", text: "SEÇÃO 4 – LICENÇA DE USO" },
      { type: "p", text: "O acesso à Plataforma Buy-Side Soluções é disponibilizado gratuitamente, a título de benefício adicional (\"bônus\"), aos adquirentes dos produtos digitais \"Manual de Compra Profissional de Sistema Fotovoltaico – Solar Buy-Side\" e \"Código do Vendedor Consultivo\", observadas as condições estabelecidas nestes Termos de Uso." },
      { type: "p", text: "A Buy-Side Soluções concede ao Usuário uma licença de uso limitada, pessoal, precária, revogável, intransferível, não sublicenciável e não exclusiva para acesso e utilização da Plataforma pelo prazo de 6 (seis) meses, contados da data de criação e ativação da conta de usuário." },
      { type: "p", text: "O acesso à Plataforma depende de cadastro prévio mediante criação de login e senha de uso exclusivo do Usuário, sendo vedado o compartilhamento de credenciais com terceiros." },
      { type: "p", text: "Decorrido o prazo de 6 (seis) meses, a licença de uso será automaticamente encerrada, independentemente de aviso prévio, salvo se houver renovação, prorrogação ou nova autorização expressamente concedida pela Buy-Side Soluções." },
      { type: "p", text: "Nenhum direito de propriedade intelectual é transferido ao Usuário." },
      { type: "heading", text: "SEÇÃO 5 – PROPRIEDADE INTELECTUAL, METODOLOGIA PROPRIETÁRIA E CONFIDENCIALIDADE" },
      { type: "p", text: "5.1. A metodologia de avaliação desenvolvida pela Buy-Side Soluções, incluindo critérios técnicos, critérios comerciais, parâmetros de análise, algoritmos, fórmulas matemáticas, fatores de ponderação, indicadores de desempenho, modelos estatísticos, sistemas de classificação, banco de dados, relatórios, rankings, pontuações, índices comparativos, conteúdos técnicos e documentos de referência, constitui ativo intelectual exclusivo e confidencial da Buy-Side Soluções." },
      { type: "p", text: "5.2. As pontuações, classificações, rankings, pareceres e avaliações disponibilizados pela Plataforma são resultados da aplicação da Metodologia Proprietária Buy-Side Soluções e destinam-se exclusivamente ao uso privado e individual do Usuário." },
      { type: "p", text: "5.3. O Usuário compromete-se a não:" },
      { type: "p", text: "a) copiar, reproduzir, armazenar, distribuir ou divulgar qualquer parte da metodologia;" },
      { type: "p", text: "b) divulgar a terceiras pontuações, rankings, classificações ou relatórios gerados pela Plataforma;" },
      { type: "p", text: "c) utilizar as informações para criação de bancos de dados, comparadores, rankings ou metodologias concorrentes;" },
      { type: "p", text: "d) realizar engenharia reversa, mineração de dados ou qualquer procedimento destinado a identificar os critérios, pesos, algoritmos ou regras da metodologia;" },
      { type: "p", text: "e) utilizar avaliações, rankings ou relatórios para fins comerciais, promocionais ou publicitários sem autorização expressa da Buy-Side Soluções." },
      { type: "p", text: "5.4. Todas as informações relativas à metodologia, pontuações, critérios de avaliação e relatórios deverão ser tratadas como confidenciais, permanecendo protegidas mesmo após o encerramento do acesso do Usuário." },
      { type: "p", text: "5.5. A Buy-Side Soluções poderá adotar todas as medidas administrativas, contratuais e judiciais cabíveis para proteção de sua propriedade intelectual e de seus segredos comerciais." },
      { type: "heading", text: "SEÇÃO 6 – INDEPENDÊNCIA DAS AVALIAÇÕES" },
      { type: "p", text: "6.1. A Buy-Side Soluções atua de forma independente na elaboração de suas avaliações." },
      { type: "p", text: "6.2. A Plataforma não representa fabricantes, distribuidores, importadores, integradores, instituições financeiras, certificadoras, órgãos reguladores ou quaisquer terceiros relacionados ao setor fotovoltaico." },
      { type: "p", text: "6.3. As avaliações disponibilizadas refletem exclusivamente a aplicação da Metodologia Solar Buy-Side e o entendimento técnico de seus desenvolvedores." },
      { type: "heading", text: "SEÇÃO 7 – NATUREZA DAS PONTUAÇÕES E CLASSIFICAÇÕES" },
      { type: "p", text: "7.1. O Usuário reconhece que todas as pontuações, classificações, rankings, pareceres e avaliações disponibilizados pela Plataforma constituem opiniões técnicas especializadas resultantes da aplicação de metodologia própria e exclusiva." },
      { type: "p", text: "7.2. As pontuações atribuídas pela Plataforma representam exclusivamente uma opinião técnica especializada da Buy-Side Soluções, resultante da aplicação de metodologia própria, não constituindo fato objetivo, verdade absoluta de mercado ou certificação oficial de desempenho dos fabricantes, equipamentos ou fornecedores avaliados." },
      { type: "p", text: "7.3. As avaliações não constituem:" },
      { type: "p", text: "a) certificação oficial de produto, fabricante, equipamento ou fornecedor;" },
      { type: "p", text: "b) homologação técnica emitida por órgão público ou entidade certificadora;" },
      { type: "p", text: "c) laudo técnico independente;" },
      { type: "p", text: "d) garantia de qualidade, durabilidade, desempenho ou rentabilidade futura;" },
      { type: "p", text: "e) recomendação obrigatória de compra, contratação ou investimento;" },
      { type: "p", text: "f) declaração absoluta de superioridade ou inferioridade entre fabricantes, equipamentos ou fornecedores." },
      { type: "heading", text: "SEÇÃO 8 – AUSÊNCIA DE GARANTIA DE RESULTADOS" },
      { type: "p", text: "8.1. A Buy-Side Soluções não garante que equipamentos, fabricantes ou propostas melhor classificados produzirão necessariamente os melhores resultados para todos os usuários." },
      { type: "p", text: "8.2. A decisão final de contratação, investimento ou aquisição permanece sendo de exclusiva responsabilidade do Usuário." },
      { type: "p", text: "8.3. A Plataforma constitui ferramenta de apoio à decisão e não substitui análises técnicas, jurídicas, financeiras ou empresariais individualizadas." },
      { type: "heading", text: "SEÇÃO 9 – LIMITAÇÃO DE RESPONSABILIDADE" },
      { type: "p", text: "9.1. Na máxima extensão permitida pela legislação aplicável, a Buy-Side Soluções não será responsável por:" },
      { type: "p", text: "a) decisões de compra ou investimento tomadas pelo Usuário;" },
      { type: "p", text: "b) prejuízos decorrentes da contratação de fornecedores;" },
      { type: "p", text: "c) perdas financeiras, lucros cessantes ou perda de oportunidade;" },
      { type: "p", text: "d) alterações posteriores em produtos, fabricantes, garantias ou condições de mercado;" },
      { type: "p", text: "e) indisponibilidade temporária da Plataforma." },
      { type: "p", text: "9.2. As informações fornecidas possuem caráter exclusivamente informativo e consultivo." },
      { type: "p", text: "9.3. A responsabilidade total da Buy-Side Soluções, quando legalmente aplicável, ficará limitada ao valor efetivamente pago pelo Usuário pela aquisição de Manual de Compra de Sistema Fotovoltaico- Solar Buy-Side nos 12 (doze) meses anteriores ao evento que originar eventual reclamação." },
      { type: "heading", text: "SEÇÃO 10 – ATUALIZAÇÃO DA METODOLOGIA" },
      { type: "p", text: "10.1. A Buy-Side Soluções poderá revisar, aperfeiçoar, atualizar ou substituir parcial ou integralmente sua metodologia a qualquer momento." },
      { type: "p", text: "10.2. O Usuário reconhece que não possui qualquer direito adquirido sobre critérios, fórmulas, pesos, algoritmos ou versões anteriores da metodologia." },
      { type: "heading", text: "SEÇÃO 11 – PRIVACIDADE E PROTEÇÃO DE DADOS" },
      { type: "p", text: "O tratamento de dados pessoais observará a Lei Geral de Proteção de Dados (Lei nº 13.709/2018) e a Política de Privacidade vigente da Plataforma." },
      { type: "heading", text: "SEÇÃO 12 – LINKS DE TERCEIROS" },
      { type: "p", text: "A Plataforma poderá conter links para websites de terceiros." },
      { type: "p", text: "A Buy-Side Soluções não se responsabiliza pelo conteúdo, políticas, práticas ou serviços disponibilizados por terceiros." },
      { type: "heading", text: "SEÇÃO 13 – SUSPENSÃO E ENCERRAMENTO DE CONTAS" },
      { type: "p", text: "A Buy-Side Soluções poderá suspender ou encerrar o acesso do Usuário, independentemente de aviso prévio, em caso de:" },
      { type: "p", text: "a) violação destes Termos;" },
      { type: "p", text: "b) compartilhamento de credenciais;" },
      { type: "p", text: "c) uso indevido da Plataforma;" },
      { type: "p", text: "d) tentativa de engenharia reversa;" },
      { type: "p", text: "e) utilização fraudulenta ou abusiva dos serviços." },
      { type: "heading", text: "SEÇÃO 14 – ALTERAÇÃO DOS TERMOS" },
      { type: "p", text: "A Buy-Side Soluções poderá alterar estes Termos de Uso a qualquer momento." },
      { type: "p", text: "A continuidade de utilização da Plataforma após a publicação das alterações será considerada aceitação integral da nova versão." },
      { type: "heading", text: "SEÇÃO 15 – LEGISLAÇÃO APLICÁVEL E FORO" },
      { type: "p", text: "Os presentes Termos serão regidos pelas leis da República Federativa do Brasil." },
      { type: "p", text: "Fica eleito o Foro da Comarca de Maringá, Estado do Paraná, para dirimir quaisquer controvérsias decorrentes destes Termos, com renúncia expressa a qualquer outro foro." },
      { type: "heading", text: "SEÇÃO 16 – DIREITO DE RESPOSTA E CANAL DE CONTESTAÇÃO TÉCNICA" },
      { type: "p", text: "16.1. A Buy-Side Soluções compromete-se a manter a independência, imparcialidade e integridade técnica de sua metodologia de avaliação." },
      { type: "p", text: "16.2. Fabricantes, distribuidores, importadores, integradores, fornecedores ou demais interessados poderão encaminhar informações técnicas, comerciais ou documentais relacionadas aos produtos avaliados pela Plataforma." },
      { type: "p", text: "16.3. As solicitações deverão ser apresentadas pelos canais oficiais disponibilizados pela Buy-Side Soluções e acompanhadas de documentação técnica suficiente para análise." },
      { type: "p", text: "16.4. O recebimento de informações complementares não gera obrigação de revisão, alteração ou exclusão de pontuações, rankings ou classificações." },
      { type: "p", text: "16.5. A decisão sobre eventual revisão permanecerá sob exclusivo critério técnico da Buy-Side Soluções." },
      { type: "p", text: "16.6. Nenhuma pressão comercial, patrocínio, relacionamento comercial ou interesse econômico poderá obrigar a Buy-Side Soluções a modificar sua metodologia ou os resultados obtidos mediante sua aplicação." },
      { type: "p", text: "16.7. Caso considere as informações apresentadas relevantes e tecnicamente fundamentadas, a Buy-Side Soluções poderá realizar nova análise e promover eventual atualização das avaliações." },
      { type: "p", text: "16.8. A abertura de procedimento de revisão ou eventual atualização de pontuações não implicará reconhecimento de erro, falha metodológica ou responsabilidade da Buy-Side Soluções." },
      { type: "p", text: "16.9. Os pedidos de contestação, documentos apresentados e análises internas poderão ser tratados como confidenciais, não havendo obrigação de divulgação dos critérios internos, pesos, algoritmos, modelos matemáticos ou demais elementos protegidos da Metodologia Proprietária Solar Buy-Side." },
      { type: "heading", text: "SEÇÃO 17 – CONTATO" },
      { type: "p", text: "Dúvidas, solicitações ou comunicações relacionadas à Plataforma poderão ser encaminhadas para:" },
      { type: "p", text: "contato@buyside.com.br" },
    ],
  },
  {
    slug: "privacidade",
    title: "Política de Privacidade",
    subtitle: "Como tratamos e protegemos os seus dados pessoais.",
    blocks: [
      { type: "p", text: "A Buy-Side Soluções Inova Simples, pessoa jurídica de direito privado, com sede na Av. Bento Munhoz da Rocha Netto, 632, 19 ANDAR, SALAS 1905, 1906, 1907 E 1908 – EVOA, CEP: 87.030-010 Maringá-PR, inscrita no CNPJ sob o nº 55.463.06/0001-80 (“Plataforma de Avaliação de Proposta Comercial de Sistema Fotovoltaico Solar Buy-Side” ou “nós”) leva a sua privacidade a sério e zela pela segurança e proteção de dados de todos os seus clientes, parceiros, fornecedores e usuários (“Usuários” ou “você”) do site “https://solarbuyside-platform.vercel.app/login” e qualquer outro site, Loja, aplicativo operado por nós (aqui designados, simplesmente, “nós ou Plataforma”)." },
      { type: "p", text: "Esta Política de Privacidade destina-se a informá-lo sobre o modo como nós utilizamos e divulgamos informações coletadas em suas visitas à nossa Loja e em mensagens que trocamos com você (“Comunicações”)." },
      { type: "p", text: "AO ACESSAR A PLATAFORMA, ENVIAR COMUNICAÇÕES OU FORNECER QUALQUER TIPO DE DADO PESSOAL, VOCÊ DECLARA ESTAR CIENTE E DE ACORDO COM ESTA POLÍTICA DE PRIVACIDADE, A QUAL DESCREVE AS FINALIDADES E FORMAS DE TRATAMENTO DE SEUS DADOS PESSOAIS QUE VOCÊ DISPONIBILIZAR NA LOJA." },
      { type: "p", text: "Esta Política de Privacidade fornece uma visão geral de nossas práticas de privacidade e das escolhas que você pode fazer, bem como direitos que você pode exercer em relação aos Dados Pessoais tratados por nós. Se você tiver alguma dúvida sobre o uso de Dados Pessoais, entre em contato com contato@buyside.com.br." },
      { type: "p", text: "Além disso, a Política de Privacidade não se aplica a quaisquer aplicativos, produtos, serviços, site ou recursos de mídia social de terceiros que possam ser oferecidos ou acessados por meio da Plataforma. O acesso a esses links fará com que você deixe a Plataforma e possa resultar na coleta ou compartilhamento de informações sobre você por terceiros. Nós não controlamos, endossamos ou fazemos quaisquer representações sobre esses sites de terceiros ou suas práticas de privacidade, que podem ser diferentes das nossas. Recomendamos que você revise a política de privacidade de qualquer site com o qual você interaja antes de permitir a coleta e o uso de seus Dados Pessoais." },
      { type: "p", text: "Caso você nos envie Dados Pessoais referentes a outras pessoas físicas, você declara ter a competência para fazê-lo e declara ter obtido o consentimento necessário para autorizar o uso de tais informações nos termos desta Política de Privacidade." },
      { type: "heading", text: "Definições" },
      { type: "p", text: "“Dados Pessoais” significa qualquer informação que, direta ou indiretamente, identifique ou possa identificar uma pessoa natural, como por exemplo, nome, CPF, data de nascimento, endereço IP, dentre outros." },
      { type: "p", text: "“Dados Pessoais Sensíveis” significa qualquer informação que revele, em relação a uma pessoa natural, origem racial ou étnica, convicção religiosa, opinião política, filiação a sindicato ou a organização de caráter religioso, filosófico ou político, dado referente à saúde ou à vida sexual, dado genético ou biométrico." },
      { type: "p", text: "“Tratamento de Dados Pessoais” significa qualquer operação efetuada no âmbito dos Dados Pessoais, por meio de meios automáticos ou não, tal como a recolha, gravação, organização, estruturação, armazenamento, adaptação ou alteração, recuperação, consulta, utilização, divulgação por transmissão, disseminação ou, alternativamente, disponibilização, harmonização ou associação, restrição, eliminação ou destruição. Também é considerado Tratamento de Dados Pessoais qualquer outra operação prevista nos termos da legislação aplicável." },
      { type: "p", text: "“Leis de Proteção de Dados” significa todas as disposições legais que regulem o Tratamento de Dados Pessoais, incluindo, porém sem se limitar, a Lei nº 13.709/18, Lei Geral de Proteção de Dados Pessoais (“LGPD”)." },
      { type: "heading", text: "Uso de Dados Pessoais" },
      { type: "p", text: "Coletamos e usamos Dados Pessoais para gerenciar seu relacionamento conosco e melhor atendê-lo quando você estiver utilizando a Plataforma, personalizando e melhorando sua experiência. Exemplos de como usamos os dados incluem:" },
      { type: "p", text: "Viabilizar que você utiliza a Plataforma." },
      { type: "p", text: "Confirmar ou corrigir as informações que temos sobre você." },
      { type: "p", text: "Enviar informações que acreditamos ser do seu interesse." },
      { type: "p", text: "Personalizar sua experiência de uso da Plataforma." },
      { type: "p", text: "Personalizar o envio de publicidades baseada no seu interesse." },
      { type: "p", text: "Entrar em contato por telefone e/ou e-mail fornecidos, nos termos da lei e para fins comerciais razoáveis." },
      { type: "p", text: "Além disso, os Dados Pessoais fornecidos também podem ser utilizados na forma que julgarmos necessária ou adequada: (a) nos termos das Leis de Proteção de Dados; (b) para atender exigências de processo judicial; (c) para cumprir decisão judicial, decisão regulatória ou decisão de autoridades competentes, incluindo autoridades fora do país de residência; (d) para proteger nossas operações; (e) para proteger direitos, privacidade e segurança nossos, seus ou de terceiros; (f) para detectar e prevenir fraude; (g) permitir-nos usar as ações disponíveis ou limitar danos que venhamos a sofrer; (h) de outros modos permitidos por lei." },
      { type: "p", text: "A NOSSA PLATAFORMA NÃO SE DESTINA A PESSOAS COM MENOS DE 18 (DEZOITO) ANOS E PEDIMOS QUE TAIS PESSOAS NÃO NOS FORNEÇAM QUALQUER DADO PESSOAL." },
      { type: "heading", text: "Não fornecimento de Dados Pessoais" },
      { type: "p", text: "Você não é obrigado a compartilhar os Dados Pessoais que solicitamos; no entanto, se você optar por não os compartilhar, em alguns casos, não poderemos fornecer a você acesso completo à Plataforma, alguns recursos especializados ou ser capaz de prestar a assistência necessária ou, ainda, viabilizar o acesso a Plataforma oferecido por você." },
      { type: "heading", text: "Dados coletados" },
      { type: "p", text: "Algumas funcionalidades podem depender de cadastro e envio de Dados Pessoais para concluir o acesso e uso da Plataforma." },
      { type: "p", text: "No contato com a Plataforma, nós podemos coletar:" },
      { type: "p", text: "Dados de contato: nome, sobrenome, telefone, cidade, Estado e e-mail." },
      { type: "p", text: "Informações que você envia: via formulário (dúvidas, reclamações, sugestões, críticas, elogios etc.)." },
      { type: "p", text: "Na navegação geral na Plataforma, nós poderemos coletar:" },
      { type: "p", text: "Dados de localização: geolocalização quando você acessa a Plataforma." },
      { type: "p", text: "Preferências: informações sobre preferências e interesses em relação ao uso da plataforma." },
      { type: "p", text: "Dados de navegação: visitas e atividades, navegador e dispositivo, endereço IP, localização e site de origem." },
      { type: "p", text: "Dados anônimos ou agregados: respostas anônimas para pesquisas ou informações agregadas sobre uso da Plataforma." },
      { type: "p", text: "Outras informações: dados de uso da Plataforma e informações coletadas por cookies, pixel tags e tecnologias similares." },
      { type: "p", text: "Ao menos que você informe em algum formulário livre preenchido por você, nós não coletamos Dados Pessoais Sensíveis." },
      { type: "heading", text: "Compartilhamento de Dados Pessoais com terceiros" },
      { type: "p", text: "Nós poderemos compartilhar seus Dados Pessoais:" },
      { type: "p", text: "Com empresas parceiras, provedores de serviços ou parceiros para gerenciar ou suportar operações comerciais em nosso nome." },
      { type: "p", text: "Com terceiros, com o objetivo de nos ajudar a gerenciar a Plataforma." },
      { type: "p", text: "Com terceiros, caso ocorra reorganização, fusão, venda, joint venture, cessão ou transferência da empresa." },
      { type: "heading", text: "Transferências internacionais de Dados" },
      { type: "p", text: "Dados Pessoais e informações de outras naturezas coletadas por nós podem ser transferidos ou acessados por entidades pertencentes ao grupo corporativo das empresas parceiras em todo o mundo de acordo com esta Política de Privacidade." },
      { type: "heading", text: "Forma de coleta automática de Dados Pessoais" },
      { type: "p", text: "Quando você visita a Plataforma, ela pode armazenar ou recuperar informações em seu navegador, seja na forma de cookies e de outras tecnologias semelhantes. Essas informações são usadas principalmente para que a Plataforma funcione como você espera." },
      { type: "p", text: "De acordo com esta Política de Privacidade, nós e nossos prestadores de serviços terceirizados podemos coletar seus Dados Pessoais de diversas formas:" },
      { type: "p", text: "Por meio do navegador ou do dispositivo: tipo de computador, resolução, sistema operacional, modelo do dispositivo, idioma e navegador." },
      { type: "p", text: "Uso de cookies: tempo de navegação, páginas visitadas, preferências e dados de tráfego anônimos." },
      { type: "p", text: "Pixel tags e tecnologias similares: medem o sucesso das campanhas e coletam dados estatísticos." },
      { type: "p", text: "Caso não deseje que suas informações sejam coletadas por meio de cookies, você pode configurar as preferências no menu do seu navegador. Para saber mais:" },
      { type: "p", text: "Google Chrome" },
      { type: "p", text: "Mozilla Firefox" },
      { type: "p", text: "Safari" },
      { type: "p", text: "Internet Explorer" },
      { type: "p", text: "Microsoft Edge" },
      { type: "p", text: "Opera" },
      { type: "p", text: "Facebook" },
      { type: "p", text: "Google" },
      { type: "p", text: "Bing" },
      { type: "heading", text: "Direitos do Usuário" },
      { type: "p", text: "Você pode, a qualquer momento, requerer: (i) confirmação de que seus Dados Pessoais estão sendo tratados; (ii) acesso aos seus Dados Pessoais; (iii) correções a dados incompletos, inexatos ou desatualizados; (iv) anonimização, bloqueio ou eliminação de dados desnecessários, excessivos ou tratados em desconformidade com o disposto em lei; (v) portabilidade de Dados Pessoais; (vi) eliminação de Dados Pessoais tratados com seu consentimento; (vii) informações sobre entidades com as quais os Dados Pessoais foram compartilhados; (viii) informações sobre a possibilidade de não fornecer consentimento e sobre as consequências da negativa; e (ix) revogação do consentimento." },
      { type: "p", text: "Os seus pedidos serão tratados com especial cuidado de forma a assegurar a eficácia dos seus direitos. Poderá lhe ser pedido que faça prova da sua identidade." },
      { type: "p", text: "Em certos casos (por exemplo, requisitos legais), o seu pedido poderá não ser imediatamente satisfeito." },
      { type: "heading", text: "Segurança dos Dados Pessoais" },
      { type: "p", text: "Buscamos adotar as medidas técnicas e organizacionais previstas pelas Leis de Proteção de Dados adequadas para proteção dos Dados Pessoais. Nenhuma transmissão ou sistema de armazenamento de dados tem a garantia de serem 100% seguros. Caso tenha motivos para acreditar que sua interação conosco tenha deixado de ser segura, favor nos notificar imediatamente." },
      { type: "heading", text: "Links de hipertexto para outros sites e redes sociais" },
      { type: "p", text: "A Plataforma poderá conter links de hipertexto que redirecionará você para sites de parceiros, anunciantes e fornecedores. Cada site possui suas próprias práticas de privacidade e não somos responsáveis por essas políticas. Consulte as políticas antes de enviar quaisquer Dados Pessoais." },
      { type: "p", text: "Não nos responsabilizamos pelas políticas e práticas de coleta, uso e divulgação de outras organizações, como Facebook, Apple, Google, Microsoft e outras. Recomendamos que você se informe sobre a política de privacidade de cada site visitado." },
      { type: "heading", text: "Atualizações desta Política de Privacidade" },
      { type: "p", text: "Se modificarmos nossa Política de Privacidade, publicaremos o novo texto na Plataforma, com a data de revisão atualizada. Podemos alterar esta Política a qualquer momento. Caso haja alteração significativa, podemos informá-lo por meio de contato ou por notificação na Plataforma." },
      { type: "p", text: "Sua utilização da Plataforma após as alterações significa que aceitou as Políticas revisadas. Caso não esteja de acordo, favor encerrar o acesso à Plataforma." },
      { type: "heading", text: "Pessoa responsável do tratamento dos Dados Pessoais" },
      { type: "p", text: "Caso pretenda exercer qualquer um dos direitos previstos nesta Política de Privacidade e/ou nas Leis de Proteção de Dados, ou resolver quaisquer dúvidas, favor contatar-nos através do e-mail contato@buyside.com.br." },
    ],
  },
  {
    slug: "medidas-antipirataria",
    title: "Medidas Antipirataria",
    subtitle: "Propriedade intelectual e proteção do conteúdo.",
    blocks: [
      { type: "heading", text: "CLÁUSULA DE PROPRIEDADE E CONFIDENCIALIDADE" },
      { type: "p", text: "é de propriedade exclusiva da Buy-Side Soluções Inova Simples, pessoa jurídica de direito privado, inscrita no CNPJ/MF sob o n.º 55.463.086/0001-80, com sede na Av. Bento Munhoz da Rocha Netto, 632, 19º Andar, Salas 1905, 1906, 1907 e 1908 — Zona 7, CEP: 87.030-010, Maringá–PR." },
      { type: "p", text: "Todos os direitos sobre a Plataforma — incluindo direitos autorais, marcas, patentes, logotipo e quaisquer outros direitos de propriedade intelectual — são reservados." },
      { type: "heading", text: "USO RESTRITO" },
      { type: "p", text: "A Plataforma é de uso exclusivo da pessoa ou empresa que adquiriu o Manual de Compra de Sistema Fotovoltaico-Solar Buy-Side e do Código do Vendedor Consultivo. É proibida a divulgação, reprodução, distribuição, comercialização, comunicação pública ou qualquer outra forma de compartilhamento dos seus conteúdos, seja total ou parcial, sem a autorização prévia e por escrito da Buy-Side Soluções." },
      { type: "heading", text: "CONSEQUÊNCIAS LEGAIS E MEDIDAS ANTIPIRATARIA" },
      { type: "p", text: "O não cumprimento dessas regras pode gerar responsabilidade civil e criminal, além de medidas judiciais para proteger os direitos da Buy-Side Soluções, incluindo indenização por danos materiais e morais." },
      { type: "p", text: "A Plataforma Solar Buy-Side de Avaliação de Proposta Comercial de Sistema Fotovoltaico é protegida por direitos autorais e tecnologias avançadas de segurança. Qualquer cópia, compartilhamento ou comercialização do seu conteúdo e método não autorizada — seja na Internet, em redes sociais, grupos de WhatsApp, Telegram ou outras plataformas e canais digitais — é uma violação grave da lei." },
      { type: "p", text: "Realizamos monitoramento contínuo na Internet, em plataformas de intermediação de infoproduto e de SaaS, em redes sociais e em dezenas de grupos de mensagens de profissionais do setor solar para identificar qualquer distribuição ilegal deste conteúdo. Se o compartilhamento indevido for detectado, o(s) responsável(is) estará(ão) sujeito(s) a sanções legais, incluindo processos civis e criminais por violação de direitos autorais, conforme a legislação vigente." },
    ],
  },
];

export function getLegalDoc(slug: string): LegalDoc | undefined {
  return LEGAL_DOCS.find((d) => d.slug === slug);
}
