import type { ScoreDefinition } from "./types";

export const companyScoreDefinitions = [
  {
    key: "company.solar_since_year",
    category: "company",
    section: "A empresa de solar",
    label: "Atuação no ramo solar",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Empresas",
    sourceRow: 7,
    rubric: "10 se >=10 anos, 7 se 5-9, 4 se 2-4, 1 se <2.",
  },
  {
    key: "company.founded_year",
    category: "company",
    section: "A empresa de solar",
    label: "Ano de abertura da empresa",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Empresas",
    sourceRow: 8,
    rubric: "10 se >=15 anos de existencia, 7 se 8-14, 4 se 3-7, 1 se <3.",
  },
  {
    key: "company.crea_registration",
    category: "company",
    section: "A empresa de solar",
    label: "Registro CREA engenharia elétrica",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Empresas",
    sourceRow: 9,
    rubric: "10 se sim, 1 se nao.",
  },
  {
    key: "company.engineer_graduation_year",
    category: "company",
    section: "A empresa de solar",
    label: "Ano de colação de grau do engenheiro",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Empresas",
    sourceRow: 10,
    rubric: "10 se >=10 anos formado, 7 se 5-9, 4 se 2-4, 1 se <2.",
  },
  {
    key: "company.installed_systems",
    category: "company",
    section: "A empresa de solar",
    label: "Quantidade de SFV instalado",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Empresas",
    sourceRow: 11,
    rubric: "10 se >100, 7 se 50-100, 4 se 10-49, 1 se <10.",
  },
  {
    key: "company.own_installation_team",
    category: "company",
    section: "A empresa de solar",
    label: "Instalações são feitas por funcionário próprio",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Empresas",
    sourceRow: 12,
    rubric: "10 se sim, 5 se terceirizado conhecido, 1 se nao.",
  },
  {
    key: "company.installation_deadline",
    category: "company",
    section: "Comprometimento da empresa",
    label: "Prazo de instalação do sistema solar",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Empresas",
    sourceRow: 14,
    rubric: "10 se <=30 dias, 7 se 31-45, 4 se 46-60, 1 se >60.",
  },
  {
    key: "company.execution_warranty",
    category: "company",
    section: "Comprometimento da empresa",
    label: "Garantia contra defeito de projeto e execução",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Empresas",
    sourceRow: 15,
    rubric: "10 se >=5 anos, 7 se 3-4, 4 se 1-2, 1 se <1.",
  },
  {
    key: "company.maintenance_support",
    category: "company",
    section: "Assistência técnica e manutenção",
    label: "Apresentou prova de manutenção e assistência",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Empresas",
    sourceRow: 17,
    rubric: "10 se sim, 1 se nao.",
  },
  {
    key: "company.support_deadline",
    category: "company",
    section: "Assistência técnica e manutenção",
    label: "Prazo de assistência técnica",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Empresas",
    sourceRow: 18,
    rubric: "10 se <=3 dias, 7 se 4-7, 4 se 8-15, 1 se >15.",
  },
  {
    key: "company.technical_docs_delivered",
    category: "company",
    section: "Final da instalação",
    label: "Memorial descritivo e diagrama unifilar",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Empresas",
    sourceRow: 20,
    rubric: "10 se sim, 1 se nao.",
  },
  {
    key: "company.seller_trust",
    category: "company",
    section: "Avaliacao do vendedor",
    label: "Competência e confiança com o vendedor",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Empresas",
    sourceRow: 22,
    rubric: "Subjetivo: 1 a 10 segundo percepcao do comprador.",
  },
  {
    key: "company.reclame_aqui",
    category: "company",
    section: "Avaliacao do vendedor",
    label: "Reclame Aqui: nota média dos últimos 12 meses",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Empresas",
    sourceRow: 23,
    rubric: "Campo comparativo da planilha. Pode ser pontuado manualmente.",
  },
] satisfies ScoreDefinition[];

export const technicalScoreDefinitions = [
  {
    key: "technical.system_power_kwp",
    category: "technical",
    section: "Sistema solar fotovoltaico",
    label: "Potência do sistema",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Tecnologica",
    sourceRow: 7,
    rubric: "Pontuacao proporcional ao kWp ofertado versus necessidade.",
  },
  {
    key: "technical.annual_generation",
    category: "technical",
    section: "Estimativa de geração",
    label: "Geração anual",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Tecnologica",
    sourceRow: 10,
    rubric: "Mesma logica do mensal, base anual.",
  },
  {
    key: "technical.module_brand",
    category: "technical",
    section: "Módulo fotovoltaico",
    label: "Módulo - marca",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Tecnologica",
    sourceRow: 12,
    rubric: "10 se Tier 1 reconhecida, 5 se Tier 2, 1 se desconhecida.",
  },
  {
    key: "technical.module_model",
    category: "technical",
    section: "Módulo fotovoltaico",
    label: "Módulo - modelo",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Tecnologica",
    sourceRow: 13,
    rubric: "10 se modelo atual de linha, 4 se descontinuado ou antigo.",
  },
  {
    key: "technical.module_power_w",
    category: "technical",
    section: "Módulo fotovoltaico",
    label: "Módulo - potência",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Tecnologica",
    sourceRow: 14,
    rubric: "10 se >=550W, 7 se 450-549W, 4 se 350-449W, 1 se <350W.",
  },
  {
    key: "technical.module_efficiency_pct",
    category: "technical",
    section: "Módulo fotovoltaico",
    label: "Módulo - eficiência",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Tecnologica",
    sourceRow: 16,
    rubric: "10 se >=22%, 7 se 20-21,9%, 4 se 18-19,9%, 1 se <18%.",
  },
  {
    key: "technical.module_lifetime_efficiency_pct",
    category: "technical",
    section: "Módulo fotovoltaico",
    label: "Módulo - eficiência aos 25 ou 30 anos",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Tecnologica",
    sourceRow: 17,
    rubric: "10 se >=85%, 7 se 80-84%, 4 se 75-79%, 1 se <75%.",
  },
  {
    key: "technical.module_defect_warranty",
    category: "technical",
    section: "Módulo fotovoltaico",
    label: "Módulo - garantia contra defeito",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Tecnologica",
    sourceRow: 18,
    rubric: "10 se >=12 anos, 7 se 8-11, 4 se 5-7, 1 se <5.",
  },
  {
    key: "technical.module_efficiency_warranty",
    category: "technical",
    section: "Módulo fotovoltaico",
    label: "Módulo - garantia de eficiência",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Tecnologica",
    sourceRow: 19,
    rubric: "10 se 30 anos, 7 se 25 anos, 4 se <25 anos.",
  },
  {
    key: "technical.inverter_brand",
    category: "technical",
    section: "Inversor de corrente",
    label: "Inversor - marca",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Tecnologica",
    sourceRow: 21,
    rubric: "10 se Tier 1, 5 se Tier 2, 1 se desconhecida.",
  },
  {
    key: "technical.inverter_model",
    category: "technical",
    section: "Inversor de corrente",
    label: "Inversor - modelo",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Tecnologica",
    sourceRow: 22,
    rubric: "10 se atual, 4 se descontinuado.",
  },
  {
    key: "technical.inverter_power_kw",
    category: "technical",
    section: "Inversor de corrente",
    label: "Inversor - potência",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Tecnologica",
    sourceRow: 23,
    rubric: "10 se compativel com kWp e sobrecarga adequada.",
  },
  {
    key: "technical.inverter_defect_warranty",
    category: "technical",
    section: "Inversor de corrente",
    label: "Inversor - garantia contra defeito",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Tecnologica",
    sourceRow: 24,
    rubric: "10 se >=10 anos, 7 se 7-9, 4 se 5-6, 1 se <5.",
  },
  {
    key: "technical.inverter_oversizing",
    category: "technical",
    section: "Sobrecarga do inversor",
    label: "Sobrecarga do inversor",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Tecnologica",
    sourceRow: 26,
    rubric: "10 se 1,25-1,35, 7 se 1,15-1,24 ou 1,36-1,45, 4 fora da faixa.",
  },
  {
    key: "technical.reputation_distributor",
    category: "technical",
    section: "Reclame Aqui",
    label: "Reputação da distribuidora",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Tecnologica",
    sourceRow: 29,
    rubric: "Nota do Reclame Aqui (0 a 10) informada pelo comprador (slide 12).",
  },
  {
    key: "technical.reputation_module_maker",
    category: "technical",
    section: "Reclame Aqui",
    label: "Reputação do fabricante do módulo",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Tecnologica",
    sourceRow: 30,
    rubric: "Nota do Reclame Aqui (0 a 10) informada pelo comprador (slide 12).",
  },
  {
    key: "technical.reputation_inverter_maker",
    category: "technical",
    section: "Reclame Aqui",
    label: "Reputação do fabricante do inversor",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Tecnologica",
    sourceRow: 31,
    rubric: "Nota do Reclame Aqui (0 a 10) informada pelo comprador (slide 12).",
  },
  {
    key: "technical.inverter_reliability",
    category: "technical",
    section: "Confiabilidade dos fabricantes",
    label: "Confiabilidade do inversor",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Tecnologica",
    sourceRow: 32,
    rubric: "10 se sim, intermediario se nao sei, baixo se nao.",
  },
  {
    key: "technical.module_reliability",
    category: "technical",
    section: "Confiabilidade dos fabricantes",
    label: "Confiabilidade do módulo",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Tecnologica",
    sourceRow: 33,
    rubric: "10 se sim, intermediario se nao sei, baixo se nao.",
  },
  {
    key: "technical.distributor_reliability",
    category: "technical",
    section: "Confiabilidade dos fabricantes",
    label: "Confiabilidade da distribuidora",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Avaliacao Tecnologica",
    sourceRow: 34,
    rubric: "10 se sim, intermediario se nao sei, baixo se nao.",
  },
] satisfies ScoreDefinition[];

/**
 * Pontuação da Viabilidade Financeira (1 a 10).
 *
 * ATENÇÃO (regra de negócio): a planilha de referência trata a Viabilidade como
 * "comparativo informativo (sem pontuação)" — porque os números financeiros das
 * propostas são facilmente manipuláveis (geração/reajuste/simultaneidade
 * inflados). A pontuação abaixo foi adicionada por decisão de produto (slide 19)
 * para somar no ranking. O RUBRIC É PROVISÓRIO e precisa de validação do Francis
 * / alinhamento com a planilha antes de ir para produção.
 */
export const financialScoreDefinitions = [
  {
    key: "financial.simple_payback",
    category: "financial",
    section: "Prazo de retorno e rentabilidade do capital",
    label: "Payback simples (meses)",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Viabilidade Financeira",
    sourceRow: 23,
    rubric: "PROVISORIO: 10 se <=48 meses, 7 se <=72, 4 se <=96, 1 se acima.",
  },
  {
    key: "financial.annual_return",
    category: "financial",
    section: "Prazo de retorno e rentabilidade do capital",
    label: "Rentabilidade do capital por mês (%)",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Viabilidade Financeira",
    sourceRow: 24,
    rubric: "PROVISORIO: 10 se >=20%, 7 se >=15%, 4 se >=10%, 1 se abaixo.",
  },
  {
    key: "financial.roi",
    category: "financial",
    section: "Prazo de retorno e rentabilidade do capital",
    label: "ROI (multiplicação por X vezes)",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Viabilidade Financeira",
    sourceRow: 25,
    rubric: "PROVISORIO: 10 se >=5x, 7 se >=4x, 4 se >=3x, 1 se abaixo.",
  },
  {
    key: "financial.viability_confidence",
    category: "financial",
    section: "Índice de inflação e fator de simultaneidade",
    label: "Confiabilidade da viabilidade",
    defaultEnabled: true,
    maxScore: 10,
    sourceSheet: "Viabilidade Financeira",
    sourceRow: 28,
    rubric: "PROVISORIO: 10 se alta, 6 se media, 3 se baixa, intermediario se nao sei.",
  },
] satisfies ScoreDefinition[];

export const scoreDefinitions = [
  ...companyScoreDefinitions,
  ...technicalScoreDefinitions,
  ...financialScoreDefinitions,
] satisfies ScoreDefinition[];
