export interface SectionEditorSchema {
  textKeys: string[]
  imageKeys: string[]
  note?: string
}

export const SECTION_EDITOR_SCHEMA: Record<string, SectionEditorSchema> = {
  hero: {
    textKeys: [
      'titlePrefix',
      'titleHighlight',
      'titleSuffix',
      'subtitle',
      'manualTitle',
      'manualSubtitle',
      'bonusBadge',
      'bonusTitle',
      'bonusSubtitle',
      'ctaButton',
      'ctaSubtext',
      'scrollHint',
    ],
    imageKeys: ['heroImage'],
  },
  context: {
    textKeys: [
      'title',
      'titleHighlight',
      'card1Title',
      'card1Desc',
      'card2Title',
      'card2Desc',
      'card3Title',
      'card3Desc',
      'check1',
      'check2',
      'check3',
      'badge',
      'subtitle',
      'alertTitle',
      'alertSubtitle',
      'solutionBadge',
      'solutionTitle',
      'solutionDesc',
      'ctaButton',
      'ctaSubtext',
    ],
    imageKeys: [],
  },
  video: {
    textKeys: [
      'title',
      'card1Title',
      'card1Desc',
      'card1Tag',
      'card2Title',
      'card2Desc',
      'card2Tag',
      'card3Title',
      'card3Desc',
      'card3Tag',
      'alertBadge',
      'alertTitle',
      'alertSubtitle',
      'videoBadge',
      'videoTitle',
      'videoDuration',
      'ctaButton',
    ],
    imageKeys: [],
  },
  audience: {
    textKeys: [
      'profile1Title',
      'profile1Desc',
      'profile1Bullet1',
      'profile1Bullet2',
      'profile1Tag',
      'profile2Title',
      'profile2Desc',
      'profile2Bullet1',
      'profile2Bullet2',
      'profile2Tag',
      'profile3Title',
      'profile3Desc',
      'profile3Bullet1',
      'profile3Bullet2',
      'profile3Tag',
      'title',
      'subtitle',
      'bottomTitle',
    ],
    imageKeys: [],
  },
  'manual-strategic': {
    textKeys: [
      'badge',
      'title',
      'subtitle',
      'description1',
      'description2',
      'description3',
      'ctaButton',
      'section2Title',
      'section2Subtitle',
      'sellSideHeader',
      'sellCard1Title',
      'sellCard1Desc',
      'sellCard2Title',
      'sellCard2Desc',
      'sellCard3Title',
      'sellCard3Desc',
      'focusHeader',
      'focusCard1Title',
      'focusCard1Desc',
      'focusCard2Title',
      'focusCard2Desc',
      'focusCard3Title',
      'focusCard3Desc',
    ],
    imageKeys: ['manualImage'],
  },
  testimonials: {
    textKeys: [
      'authorName',
      'authorRole',
      'statLabel',
      'statValue',
      'statSubtext',
      'title',
      'subtitle',
      'intro',
      'quote1',
      'quote2',
      'ctaTitle',
      'ctaText',
      'ctaButton',
    ],
    imageKeys: ['testimonialImage'],
  },
  'story-bridge': {
    textKeys: [
      'feature1Title',
      'feature1Desc',
      'feature2Title',
      'feature2Desc',
      'feature3Title',
      'feature3Desc',
      'feature4Title',
      'feature4Desc',
      'title',
      'subtitle',
    ],
    imageKeys: ['manualImage'],
  },
  'seller-code': {
    textKeys: [
      'title',
      'titleHighlight',
      'item1Title',
      'item1Desc',
      'item2Title',
      'item2Desc',
      'item3Title',
      'item3Desc',
      'item4Title',
      'item4Desc',
      'subtitle',
      'badge',
      'badgeHighlight',
      'bonusTitle',
      'bonusSubtitle',
      'listTitle',
    ],
    imageKeys: ['bookImage'],
  },
  pricing: {
    textKeys: [
      'feature1Title',
      'feature1Desc',
      'feature1Tag',
      'feature2Title',
      'feature2Desc',
      'feature2Tag',
      'feature3Title',
      'feature3Desc',
      'feature3Tag',
      'feature4Title',
      'feature4Desc',
      'feature4Tag',
      'badge',
      'title',
      'titleFirst',
      'titleSecond',
      'subtitle',
      'subtitleFirst',
      'subtitleSecond',
      'featuresTitle',
      'bonusBadge',
      'bonusTitle',
      'bonusSubtitle',
      'planBadge',
      'planTitle',
      'priceFrom',
      'priceInstallments',
      'priceValue',
      'priceCents',
      'priceUpfront',
      'ctaButton',
      'finalCtaButton',
      'benefit1',
      'benefit2',
      'benefit3',
    ],
    imageKeys: ['guarantee', 'visa', 'mastercard', 'pix', 'boleto', 'securePurchase'],
  },
  'buyer-wave': {
    textKeys: [
      'badge',
      'title',
      'subtitle',
      'card1Title',
      'card1Item1',
      'card1Item2',
      'card1Item3',
      'card2Title',
      'card2Item1',
      'card2Item2',
      'card2Item3',
      'testimonialsTitle',
      'testimonialsSubtitle',
      'ctaButton',
      'testimonial1Name',
      'testimonial1Role',
      'testimonial1Location',
      'testimonial1ObjectPosition',
      'testimonial1ReviewTitle',
      'testimonial1Quote',
      'testimonial1Highlight',
      'testimonial2Name',
      'testimonial2Role',
      'testimonial2Location',
      'testimonial2ObjectPosition',
      'testimonial2ReviewTitle',
      'testimonial2Quote',
      'testimonial2Highlight',
      'testimonial3Name',
      'testimonial3Role',
      'testimonial3Location',
      'testimonial3ObjectPosition',
      'testimonial3ReviewTitle',
      'testimonial3Quote',
      'testimonial3Highlight',
      'testimonial4Name',
      'testimonial4Role',
      'testimonial4Location',
      'testimonial4ObjectPosition',
      'testimonial4ReviewTitle',
      'testimonial4Quote',
      'testimonial4Highlight',
      'testimonial5Name',
      'testimonial5Role',
      'testimonial5Location',
      'testimonial5ObjectPosition',
      'testimonial5ReviewTitle',
      'testimonial5Quote',
      'testimonial5Highlight',
      'testimonial6Name',
      'testimonial6Role',
      'testimonial6Location',
      'testimonial6ObjectPosition',
      'testimonial6ReviewTitle',
      'testimonial6Quote',
      'testimonial6Highlight',
    ],
    imageKeys: [
      'testimonial1Avatar',
      'testimonial2Avatar',
      'testimonial3Avatar',
      'testimonial4Avatar',
      'testimonial5Avatar',
      'testimonial6Avatar',
    ],
  },
  authority: {
    textKeys: [
      'badge',
      'title',
      'titleHighlight',
      'person1Experience',
      'person1ExperienceLabel',
      'person1Badge',
      'person1Name',
      'person1Desc',
      'person1Tag',
      'person2Experience',
      'person2ExperienceLabel',
      'person2Badge',
      'person2Name',
      'person2Desc',
      'person2Tag',
    ],
    imageKeys: ['francis', 'ovidio'],
  },
  'lead-magnet': {
    textKeys: [
      'feature1',
      'feature2',
      'feature3',
      'feature4',
      'badge',
      'title',
      'titleHighlight',
      'subtitle',
      'ctaButton',
      'ctaSubtext',
      'modalTitle',
      'modalSubtitle',
      'successTitle',
      'successMessage',
    ],
    imageKeys: ['ebook'],
  },
  newsletter: {
    textKeys: [
      'title',
      'subtitle',
      'placeholder',
      'successButton',
      'ctaButton',
      'successMessage',
      'privacyNote',
    ],
    imageKeys: [],
  },
  faq: {
    textKeys: [
      'faq1Question',
      'faq1Answer',
      'faq2Question',
      'faq2Answer',
      'faq3Question',
      'faq3Answer',
      'title',
      'subtitle',
      'ctaButton',
      'sectionTitle',
    ],
    imageKeys: [],
  },
  contact: {
    textKeys: [
      'title',
      'subtitle',
      'companyName',
      'cnpjLabel',
      'cnpjValue',
      'addressLine1',
      'addressLine2',
      'addressLine3',
      'emailLabel',
      'emailAddress',
    ],
    imageKeys: [],
  },
  'privacy-policy': {
    textKeys: [],
    imageKeys: [],
    note: 'Pagina legal usa src/legal/legalContent.tsx e ainda nao esta conectada ao CMS.',
  },
  'terms-of-use': {
    textKeys: [],
    imageKeys: [],
    note: 'Pagina legal usa src/legal/legalContent.tsx e ainda nao esta conectada ao CMS.',
  },
  antipiracy: {
    textKeys: [],
    imageKeys: [],
    note: 'Pagina legal usa src/legal/legalContent.tsx e ainda nao esta conectada ao CMS.',
  },
}
