/**
 * Conteúdo dos documentos legais (Termos de Uso, Política de Privacidade,
 * Medidas Antipirataria). Texto integral extraído dos .docx oficiais em
 * /ajustes. Renderizado pelas rotas públicas /termos, /privacidade e
 * /medidas-antipirataria e referenciado no cadastro e no menu do perfil.
 */

export type LegalBlock = { type: "heading" | "p"; text: string };

export type LegalDoc = {
  slug: "termos" | "privacidade" | "medidas-antipirataria";
  title: string;
  /** Subtítulo curto exibido no topo da página. */
  subtitle: string;
  blocks: LegalBlock[];
};

export const LEGAL_DOCS: LegalDoc[] = [
  {
    slug: "termos",
    title: "Termos de Uso",
    subtitle: "Condições de uso da Plataforma Solar Buy-Side.",
    blocks: [
      { type: "p", text: "A Buy-Side Soluções Inova Simples, pessoa jurídica de direito privado, com sede na Av. Bento Munhoz da Rocha Netto, 632, 19 ANDAR, SALAS 1905, 1906, 1907 E 1908 – EVOA, CEP: 87.030-010 Maringá-PR, inscrita no CNPJ sob o nº 55.463.06/0001-80 (“Plataforma de Avaliação de Proposta Comercial de Sistema Fotovoltaico Solar Buy-Side” ou “nós”) leva a sua privacidade a sério e zela pela segurança e proteção de dados de todos os seus clientes, parceiros, fornecedores e usuários (“Usuários” ou “você”) do site “https://solarbuyside-platform.vercel.app/login” e qualquer outro site, Loja, aplicativo operado por nós (aqui designados, simplesmente, “nós ou Plataforma”)." },
      { type: "p", text: "Ao navegar nesta Plataforma, consideramos que você está de acordo com os Termos de Uso abaixo. Caso você não esteja de acordo com as condições deste contrato, pedimos que não faça mais uso dessa Plataforma, muito menos cadastre-se ou envie os seus dados pessoais." },
      { type: "p", text: "Se modificarmos nossos Termos de Uso, publicaremos o novo texto nesta Plataforma, com a data de revisão atualizada. Podemos alterar este documento a qualquer momento. Caso haja alteração significativa, podemos informá-lo por meio das informações de contato que tivermos em nosso banco de dados ou por meio de notificações." },
      { type: "p", text: "A utilização desta Plataforma após as alterações significa que você aceitou os Termos de Uso revisados. Caso, após a leitura da versão revisada, você não esteja de acordo com seus termos, favor encerrar o seu acesso." },
      { type: "heading", text: "Seção 1 – Usuário" },
      { type: "p", text: "A utilização desta Plataforma atribui de forma automática a condição de Usuário e implica a plena aceitação de todas as diretrizes e condições incluídas nestes Termos." },
      { type: "heading", text: "Seção 2 – Adesão em conjunto com a Política de Privacidade" },
      { type: "p", text: "A utilização desta Plataforma acarreta a adesão aos presentes Termos de Uso e à versão mais atualizada da Política de Privacidade de Buy-Side Soluções Inova Simples." },
      { type: "heading", text: "Seção 3 – Condições de acesso" },
      { type: "p", text: "O acesso ao website é oferecido gratuitamente como bônus para compradores dos produtos digitais “Manual de Compra de Sistema Fotovoltaico- Solar Buy-Side e do Código do Vendedor Consultivo durante um período de até 6 meses a contar da criação de uma conta e exige prévia inscrição ou registro. Portanto, para usufruir das suas funcionalidades o usuário deverá efetuar um cadastro, criando uma conta de usuário com login e senha próprios para acesso." },
      { type: "p", text: "É de total responsabilidade do usuário fornecer apenas informações corretas, autênticas, válidas, completas e atualizadas, bem como não divulgar o seu login e senha para terceiros." },
      { type: "p", text: "Caso partes desta Plataforma oferecem ao usuário a opção de publicar comentários em determinadas áreas. Buy-Side Soluções Inova Simples não consente com a publicação de conteúdos que tenham natureza discriminatória, ofensiva ou ilícita, ou ainda infrinjam direitos de autor ou quaisquer outros direitos de terceiros." },
      { type: "p", text: "A publicação de quaisquer conteúdos pelo usuário desta Plataforma, incluindo mensagens e comentários, implica em licença não-exclusiva, irrevogável e irretratável, para sua utilização, reprodução e publicação pela Buy-Side Soluções Inova Simples no seu website, plataformas e aplicações de internet, ou ainda em outras plataformas, sem qualquer restrição ou limitação." },
      { type: "heading", text: "Seção 4 – Cookies" },
      { type: "p", text: "Informações sobre o seu uso nesta Plataforma podem ser coletadas a partir de cookies. Cookies são informações armazenadas diretamente no computador que você está utilizando. Os cookies permitem a coleta de informações como tipo de navegador, tempo dispendido, páginas visitadas, preferências de idioma e outros dados de tráfego anônimos." },
      { type: "p", text: "Nós e nossos prestadores de serviços utilizamos informações para proteção de segurança, facilitar a navegação, exibir informações de modo mais eficiente e personalizar sua experiência, assim como para rastreamento online." },
      { type: "p", text: "Caso não deseje que suas informações sejam coletadas por meio de cookies, há um procedimento simples na maior parte dos navegadores que permite que os cookies sejam automaticamente rejeitados, ou oferece a opção de aceitar ou rejeitar a transferência de um cookie (ou cookies) específico(s)." },
      { type: "p", text: "As definições que escolher podem afetar a sua experiência de navegação e o funcionamento que exige a utilização de cookies. Rejeitamos qualquer responsabilidade pelas consequências resultantes do funcionamento limitado desta Plataforma provocado pela desativação de cookies no seu dispositivo." },
      { type: "heading", text: "Seção 5 – Propriedade Intelectual" },
      { type: "p", text: "Todos os elementos de Buy-Side Soluções Inova Simples são de propriedade intelectual da mesma ou de seus licenciados. Estes Termos ou a utilização da Plataforma não concede a você qualquer licença ou direito de uso dos direitos de propriedade intelectual da Buy-Side Soluções Inova Simples ou de terceiros." },
      { type: "heading", text: "Seção 6 – Links para sites de terceiros" },
      { type: "p", text: "Esta Plataforma poderá conter links de hipertexto que redirecionará você para sites de parceiros, anunciantes e fornecedores. Se você clicar em um desses links, lembre-se que cada site possui suas próprias práticas de privacidade e que não somos responsáveis por essas políticas." },
      { type: "p", text: "Não nos responsabilizamos pelas políticas e práticas de coleta, uso e divulgação de outras organizações. Recomendamos que você se informe sobre a política de privacidade e termos de uso de cada site visitado." },
      { type: "heading", text: "Seção 7 – Prazos e alterações" },
      { type: "p", text: "O funcionamento desta Plataforma se dá por prazo indeterminado. A Plataforma, no todo ou em cada uma de suas seções, pode ser encerrado, suspenso ou interrompido unilateralmente por Buy-Side Soluções Inova Simples, a qualquer momento e sem necessidade de prévio aviso." },
      { type: "heading", text: "Seção 8 – Dados pessoais" },
      { type: "p", text: "Durante a utilização desta Plataforma, certos dados pessoais serão coletados e tratados por Buy-Side Soluções Inova Simples e/ou pelos Parceiros. As regras relacionadas ao tratamento de dados pessoais estão estipuladas na Política de Privacidade." },
      { type: "heading", text: "Seção 9 – Contato" },
      { type: "p", text: "Caso você tenha qualquer dúvida sobre os Termos de Uso, entre em contato pelo e-mail contato@buyside.com.br." },
    ],
  },
  {
    slug: "privacidade",
    title: "Política de Privacidade",
    subtitle: "Como tratamos e protegemos os seus dados pessoais.",
    blocks: [
      { type: "p", text: "A Buy-Side Soluções Inova Simples, pessoa jurídica de direito privado, com sede na Av. Bento Munhoz da Rocha Netto, 632, 19 ANDAR, SALAS 1905, 1906, 1907 E 1908 – EVOA, CEP: 87.030-010 Maringá-PR, inscrita no CNPJ sob o nº 55.463.06/0001-80 (“Plataforma de Avaliação de Proposta Comercial de Sistema Fotovoltaico Solar Buy-Side” ou “nós”) leva a sua privacidade a sério e zela pela segurança e proteção de dados de todos os seus clientes, parceiros, fornecedores e usuários (“Usuários” ou “você”) do site “https://solarbuyside-platform.vercel.app/login” e qualquer outro site, Loja, aplicativo operado por nós (aqui designados, simplesmente, “nós ou Plataforma”)." },
      { type: "p", text: "Esta Política de Privacidade destina-se a informá-lo sobre o modo como nós utilizamos e divulgamos informações coletadas em suas visitas à nossa Loja e em mensagens que trocamos com você (“Comunicações”)." },
      { type: "p", text: "AO ACESSAR A PLATAFORMA, ENVIAR COMUNICAÇÕES OU FORNECER QUALQUER TIPO DE DADO PESSOAL, VOCÊ DECLARA ESTAR CIENTE E DE ACORDO COM ESTA POLÍTICA DE PRIVACIDADE, A QUAL DESCREVE AS FINALIDADES E FORMAS DE TRATAMENTO DE SEUS DADOS PESSOAIS QUE VOCÊ DISPONIBILIZAR NA LOJA." },
      { type: "p", text: "Esta Política de Privacidade fornece uma visão geral de nossas práticas de privacidade e das escolhas que você pode fazer, bem como direitos que você pode exercer em relação aos Dados Pessoais tratados por nós. Se você tiver alguma dúvida sobre o uso de Dados Pessoais, entre em contato com contato@buyside.com.br." },
      { type: "p", text: "Além disso, a Política de Privacidade não se aplica a quaisquer aplicativos, produtos, serviços, site ou recursos de mídia social de terceiros que possam ser oferecidos ou acessados por meio da Plataforma. O acesso a esses links fará com que você deixe a Plataforma e possa resultar na coleta ou compartilhamento de informações sobre você por terceiros. Nós não controlamos, endossamos ou fazemos quaisquer representações sobre esses sites de terceiros ou suas práticas de privacidade, que podem ser diferentes das nossas. Recomendamos que você revise a política de privacidade de qualquer site com o qual você interaja antes de permitir a coleta e o uso de seus Dados Pessoais." },
      { type: "p", text: "Caso você nos envie Dados Pessoais referentes a outras pessoas físicas, você declara ter a competência para fazê-lo e declara ter obtido o consentimento necessário para autorizar o uso de tais informações nos termos desta Política de Privacidade." },
      { type: "heading", text: "Definições" },
      { type: "p", text: "“Dados Pessoais” significa qualquer informação que, direta ou indiretamente, identifique ou possa identificar uma pessoa natural, como por exemplo, nome, CPF, data de nascimento, endereço IP, dentre outros." },
      { type: "p", text: "“Dados Pessoais Sensíveis” significa qualquer informação que revele, em relação a uma pessoa natural, origem racial ou étnica, convicção religiosa, opinião política, filiação a sindicato ou a organização de caráter religioso, filosófico ou político, dado referente à saúde ou à vida sexual, dado genético ou biométrico." },
      { type: "p", text: "“Tratamento de Dados Pessoais” significa qualquer operação efetuada no âmbito dos Dados Pessoais, por meio de meios automáticos ou não, tal como a recolha, gravação, organização, estruturação, armazenamento, adaptação ou alteração, recuperação, consulta, utilização, divulgação por transmissão, disseminação ou, alternativamente, disponibilização, harmonização ou associação, restrição, eliminação ou destruição. Também é considerado Tratamento de Dados Pessoais qualquer outra operação prevista nos termos da legislação aplicável." },
      { type: "p", text: "“Leis de Proteção de Dados” significa todas as disposições legais que regulem o Tratamento de Dados Pessoais, incluindo, porém sem se limitar, a Lei nº 13.709/18, Lei Geral de Proteção de Dados Pessoais (“LGPD”)." },
      { type: "heading", text: "Uso de Dados Pessoais" },
      { type: "p", text: "Coletamos e usamos Dados Pessoais para gerenciar seu relacionamento conosco e melhor atendê-lo quando você estiver utilizando a Plataforma, personalizando e melhorando sua experiência. Exemplos de como usamos os dados incluem:" },
      { type: "p", text: "Viabilizar que você utiliza a Plataforma." },
      { type: "p", text: "Confirmar ou corrigir as informações que temos sobre você." },
      { type: "p", text: "Enviar informações que acreditamos ser do seu interesse." },
      { type: "p", text: "Personalizar sua experiência de uso da Plataforma." },
      { type: "p", text: "Personalizar o envio de publicidades baseada no seu interesse." },
      { type: "p", text: "Entrar em contato por telefone e/ou e-mail fornecidos, nos termos da lei e para fins comerciais razoáveis." },
      { type: "p", text: "Além disso, os Dados Pessoais fornecidos também podem ser utilizados na forma que julgarmos necessária ou adequada: (a) nos termos das Leis de Proteção de Dados; (b) para atender exigências de processo judicial; (c) para cumprir decisão judicial, decisão regulatória ou decisão de autoridades competentes, incluindo autoridades fora do país de residência; (d) para proteger nossas operações; (e) para proteger direitos, privacidade e segurança nossos, seus ou de terceiros; (f) para detectar e prevenir fraude; (g) permitir-nos usar as ações disponíveis ou limitar danos que venhamos a sofrer; (h) de outros modos permitidos por lei." },
      { type: "p", text: "A NOSSA PLATAFORMA NÃO SE DESTINA A PESSOAS COM MENOS DE 18 (DEZOITO) ANOS E PEDIMOS QUE TAIS PESSOAS NÃO NOS FORNEÇAM QUALQUER DADO PESSOAL." },
      { type: "heading", text: "Não fornecimento de Dados Pessoais" },
      { type: "p", text: "Você não é obrigado a compartilhar os Dados Pessoais que solicitamos; no entanto, se você optar por não os compartilhar, em alguns casos, não poderemos fornecer a você acesso completo à Plataforma, alguns recursos especializados ou ser capaz de prestar a assistência necessária ou, ainda, viabilizar o acesso a Plataforma oferecido por você." },
      { type: "heading", text: "Dados coletados" },
      { type: "p", text: "Algumas funcionalidades podem depender de cadastro e envio de Dados Pessoais para concluir o acesso e uso da Plataforma." },
      { type: "p", text: "No contato com a Plataforma, nós podemos coletar:" },
      { type: "p", text: "Dados de contato: nome, sobrenome, telefone, cidade, Estado e e-mail." },
      { type: "p", text: "Informações que você envia: via formulário (dúvidas, reclamações, sugestões, críticas, elogios etc.)." },
      { type: "p", text: "Na navegação geral na Plataforma, nós poderemos coletar:" },
      { type: "p", text: "Dados de localização: geolocalização quando você acessa a Plataforma." },
      { type: "p", text: "Preferências: informações sobre preferências e interesses em relação ao uso da plataforma." },
      { type: "p", text: "Dados de navegação: visitas e atividades, navegador e dispositivo, endereço IP, localização e site de origem." },
      { type: "p", text: "Dados anônimos ou agregados: respostas anônimas para pesquisas ou informações agregadas sobre uso da Plataforma." },
      { type: "p", text: "Outras informações: dados de uso da Plataforma e informações coletadas por cookies, pixel tags e tecnologias similares." },
      { type: "p", text: "Ao menos que você informe em algum formulário livre preenchido por você, nós não coletamos Dados Pessoais Sensíveis." },
      { type: "heading", text: "Compartilhamento de Dados Pessoais com terceiros" },
      { type: "p", text: "Nós poderemos compartilhar seus Dados Pessoais:" },
      { type: "p", text: "Com empresas parceiras, provedores de serviços ou parceiros para gerenciar ou suportar operações comerciais em nosso nome." },
      { type: "p", text: "Com terceiros, com o objetivo de nos ajudar a gerenciar a Plataforma." },
      { type: "p", text: "Com terceiros, caso ocorra reorganização, fusão, venda, joint venture, cessão ou transferência da empresa." },
      { type: "heading", text: "Transferências internacionais de Dados" },
      { type: "p", text: "Dados Pessoais e informações de outras naturezas coletadas por nós podem ser transferidos ou acessados por entidades pertencentes ao grupo corporativo das empresas parceiras em todo o mundo de acordo com esta Política de Privacidade." },
      { type: "heading", text: "Forma de coleta automática de Dados Pessoais" },
      { type: "p", text: "Quando você visita a Plataforma, ela pode armazenar ou recuperar informações em seu navegador, seja na forma de cookies e de outras tecnologias semelhantes. Essas informações são usadas principalmente para que a Plataforma funcione como você espera." },
      { type: "p", text: "De acordo com esta Política de Privacidade, nós e nossos prestadores de serviços terceirizados podemos coletar seus Dados Pessoais de diversas formas:" },
      { type: "p", text: "Por meio do navegador ou do dispositivo: tipo de computador, resolução, sistema operacional, modelo do dispositivo, idioma e navegador." },
      { type: "p", text: "Uso de cookies: tempo de navegação, páginas visitadas, preferências e dados de tráfego anônimos." },
      { type: "p", text: "Pixel tags e tecnologias similares: medem o sucesso das campanhas e coletam dados estatísticos." },
      { type: "p", text: "Caso não deseje que suas informações sejam coletadas por meio de cookies, você pode configurar as preferências no menu do seu navegador. Para saber mais:" },
      { type: "p", text: "Google Chrome" },
      { type: "p", text: "Mozilla Firefox" },
      { type: "p", text: "Safari" },
      { type: "p", text: "Internet Explorer" },
      { type: "p", text: "Microsoft Edge" },
      { type: "p", text: "Opera" },
      { type: "p", text: "Facebook" },
      { type: "p", text: "Google" },
      { type: "p", text: "Bing" },
      { type: "heading", text: "Direitos do Usuário" },
      { type: "p", text: "Você pode, a qualquer momento, requerer: (i) confirmação de que seus Dados Pessoais estão sendo tratados; (ii) acesso aos seus Dados Pessoais; (iii) correções a dados incompletos, inexatos ou desatualizados; (iv) anonimização, bloqueio ou eliminação de dados desnecessários, excessivos ou tratados em desconformidade com o disposto em lei; (v) portabilidade de Dados Pessoais; (vi) eliminação de Dados Pessoais tratados com seu consentimento; (vii) informações sobre entidades com as quais os Dados Pessoais foram compartilhados; (viii) informações sobre a possibilidade de não fornecer consentimento e sobre as consequências da negativa; e (ix) revogação do consentimento." },
      { type: "p", text: "Os seus pedidos serão tratados com especial cuidado de forma a assegurar a eficácia dos seus direitos. Poderá lhe ser pedido que faça prova da sua identidade." },
      { type: "p", text: "Em certos casos (por exemplo, requisitos legais), o seu pedido poderá não ser imediatamente satisfeito." },
      { type: "heading", text: "Segurança dos Dados Pessoais" },
      { type: "p", text: "Buscamos adotar as medidas técnicas e organizacionais previstas pelas Leis de Proteção de Dados adequadas para proteção dos Dados Pessoais. Nenhuma transmissão ou sistema de armazenamento de dados tem a garantia de serem 100% seguros. Caso tenha motivos para acreditar que sua interação conosco tenha deixado de ser segura, favor nos notificar imediatamente." },
      { type: "heading", text: "Links de hipertexto para outros sites e redes sociais" },
      { type: "p", text: "A Plataforma poderá conter links de hipertexto que redirecionará você para sites de parceiros, anunciantes e fornecedores. Cada site possui suas próprias práticas de privacidade e não somos responsáveis por essas políticas. Consulte as políticas antes de enviar quaisquer Dados Pessoais." },
      { type: "p", text: "Não nos responsabilizamos pelas políticas e práticas de coleta, uso e divulgação de outras organizações, como Facebook, Apple, Google, Microsoft e outras. Recomendamos que você se informe sobre a política de privacidade de cada site visitado." },
      { type: "heading", text: "Atualizações desta Política de Privacidade" },
      { type: "p", text: "Se modificarmos nossa Política de Privacidade, publicaremos o novo texto na Plataforma, com a data de revisão atualizada. Podemos alterar esta Política a qualquer momento. Caso haja alteração significativa, podemos informá-lo por meio de contato ou por notificação na Plataforma." },
      { type: "p", text: "Sua utilização da Plataforma após as alterações significa que aceitou as Políticas revisadas. Caso não esteja de acordo, favor encerrar o acesso à Plataforma." },
      { type: "heading", text: "Pessoa responsável do tratamento dos Dados Pessoais" },
      { type: "p", text: "Caso pretenda exercer qualquer um dos direitos previstos nesta Política de Privacidade e/ou nas Leis de Proteção de Dados, ou resolver quaisquer dúvidas, favor contatar-nos através do e-mail contato@buyside.com.br." },
    ],
  },
  {
    slug: "medidas-antipirataria",
    title: "Medidas Antipirataria",
    subtitle: "Propriedade intelectual e proteção do conteúdo.",
    blocks: [
      { type: "heading", text: "CLÁUSULA DE PROPRIEDADE E CONFIDENCIALIDADE" },
      { type: "p", text: "é de propriedade exclusiva da Buy-Side Soluções Inova Simples, pessoa jurídica de direito privado, inscrita no CNPJ/MF sob o n.º 55.463.086/0001-80, com sede na Av. Bento Munhoz da Rocha Netto, 632, 19º Andar, Salas 1905, 1906, 1907 e 1908 — Zona 7, CEP: 87.030-010, Maringá–PR." },
      { type: "p", text: "Todos os direitos sobre a Plataforma — incluindo direitos autorais, marcas, patentes, logotipo e quaisquer outros direitos de propriedade intelectual — são reservados." },
      { type: "heading", text: "USO RESTRITO" },
      { type: "p", text: "A Plataforma é de uso exclusivo da pessoa ou empresa que adquiriu o Manual de Compra de Sistema Fotovoltaico-Solar Buy-Side e do Código do Vendedor Consultivo. É proibida a divulgação, reprodução, distribuição, comercialização, comunicação pública ou qualquer outra forma de compartilhamento dos seus conteúdos, seja total ou parcial, sem a autorização prévia e por escrito da Buy-Side Soluções." },
      { type: "heading", text: "CONSEQUÊNCIAS LEGAIS E MEDIDAS ANTIPIRATARIA" },
      { type: "p", text: "O não cumprimento dessas regras pode gerar responsabilidade civil e criminal, além de medidas judiciais para proteger os direitos da Buy-Side Soluções, incluindo indenização por danos materiais e morais." },
      { type: "p", text: "A Plataforma Solar Buy-Side de Avaliação de Proposta Comercial de Sistema Fotovoltaico é protegida por direitos autorais e tecnologias avançadas de segurança. Qualquer cópia, compartilhamento ou comercialização do seu conteúdo e método não autorizada — seja na Internet, em redes sociais, grupos de WhatsApp, Telegram ou outras plataformas e canais digitais — é uma violação grave da lei." },
      { type: "p", text: "Realizamos monitoramento contínuo na Internet, em plataformas de intermediação de infoproduto e de SaaS, em redes sociais e em dezenas de grupos de mensagens de profissionais do setor solar para identificar qualquer distribuição ilegal deste conteúdo. Se o compartilhamento indevido for detectado, o(s) responsável(is) estará(ão) sujeito(s) a sanções legais, incluindo processos civis e criminais por violação de direitos autorais, conforme a legislação vigente." },
    ],
  },
];

export function getLegalDoc(slug: string): LegalDoc | undefined {
  return LEGAL_DOCS.find((d) => d.slug === slug);
}
